### ISSUE TITLE
weird zero balance

### ISSUE THREAD

**Issue by happypeter** [nervosnetwork/ckb-explorer#145]
## How to Reproduce

As a miner, I've mined 4 blocks and got the reward through cellbase

## Expected

to see non-zero balance

## Actual Output

https://explorer.nervos.org/address/ckt1q9gry5zgckljj20cxh4k33ufu3q2kxxx2jv0cmk4ykgkhc

<img width="1294" alt="屏幕快照 2019-05-22 下午10 44 30" src="https://user-images.githubusercontent.com/72467/58184783-57446a80-7ce4-11e9-8c7e-239f1d0db052.png">

**Comment by duanyytop** [comment]
Thanks for your feedback.

We also find this issue and we are doing something to solve this issue.

We will release as soon as possible. Thanks again.

**Comment by duanyytop** [comment]
We have solved this issue. 

Thanks your feedback again.

**Comment by happypeter** [comment]
thx
