### ISSUE TITLE
Explorer reports an address as having a balance that is too large.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/ckb-explorer#1490]
**Describe the bug**

An address in the explorer is reading a CKB balance of 57 billion, which is higher than the total supply.

```
ckb1qpzuzykljldwecnuftaq9vjtzhmygqaal4z6ktsw3rylk23y09436q2q6uls60zkrl92uvcw40qrpkxed2ws4umdp3g3fzpktz34pju78wjsqqqqzqqqqqraqqqqp8gqqqqx6qqqqqgqqqqqxqqqqqr9qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqx5qqqqqsqqqqqvqqqqqrzqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq04v8fa
```

57,294,876,705.35811791 CKB

**To Reproduce**
1. Go to https://explorer.nervos.org/address/ckb1qpzuzykljldwecnuftaq9vjtzhmygqaal4z6ktsw3rylk23y09436q2q6uls60zkrl92uvcw40qrpkxed2ws4umdp3g3fzpktz34pju78wjsqqqqzqqqqqraqqqqp8gqqqqx6qqqqqgqqqqqxqqqqqr9qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqx5qqqqqsqqqqqvqqqqqrzqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq04v8fa

**Expected behavior**
I currently see the real balance at 299,061,359.61826591 CKB as reported by RPC.

**Screenshots**
![20231103174246](https://github.com/nervosnetwork/ckb-explorer/assets/37931/ca4d36f1-27b9-4da1-b578-0344dd2df091)

**Comment by Keith-CY** [comment]
It has been fixed and the balance is correct now.
