### ISSUE TITLE
The order of witnesses is not the same as that in the transaction.

### ISSUE THREAD

**Issue by chaoticlonghair** [nervosnetwork/ckb-explorer#1594]
**Environment**

- **Operating system**: Unrelated
- **Arch**: Unrelated
- **Installation**: Unrelated

**Describe the bug**

The order of witnesses is not the same as that in the transaction.

**To Reproduce**
1. Send a transaction with more than 1 witness.
   - Use different inputs whose private keys are different.
   - More witnesses will be easier to reproduce the bug.
3. Use JSON-RPC to fetch the transaction from any public CKB endpoints.
4. Two errors:
   - The witnesses in the transaction page are in an incorrect order.
   - Download the transaction from the transaction page, the witnesses are in an incorrect order.

**Expected behavior**

The witnesses should be in the same order as it in the transaction.

**Screenshots**

None.

**Additional context**

I checked, they are not in the reverse order, they are in a fully random order.

**Comment by Keith-CY** [comment]
> **Environment**
> 
> * **Operating system**: Unrelated
> * **Arch**: Unrelated
> * **Installation**: Unrelated
> 
> **Describe the bug**
> 
> The order of witnesses is not the same as that in the transaction.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Send a transaction with more than 1 witness.
>    
>    * Use different inputs whose private keys are different.
>    * More witnesses will be easier to reproduce the bug.
> 2. Use JSON-RPC to fetch the transaction from any public CKB endpoints.
> 3. Two errors:
>    
>    * The witnesses in the transaction page are in an incorrect order.
>    * Download the transaction from the transaction page, the witnesses are in an incorrect order.
> 
> **Expected behavior**
> 
> The witnesses should be in the same order as it in the transaction.
> 
> **Screenshots**
> 
> None.
> 
> **Additional context**
> 
> I checked, they are not in the reverse order, they are in a fully random order.

Please check if this field is impacted by the update for performance. @rabbitz @zmcNotafraid
