### ISSUE TITLE
How to copy the `args` of lock script from the transaction page as the format it displayed?

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb-explorer#1787]
### Description

I want to copy the lock script args and go to another page to search this args, to make sure they are the same args.

But, after the upgrade in last week (maybe two weeks ago, I guess).

When I select the args, I could NOT copy it, unless I enable web developer tools and copy it from the source of the page.

It's really a terrible user experience.

---

Maybe you could tell me that, I could copy it from the "View data as" page, but it only can copy the reverse format of the transaction page displayed.

I have tried all formats in "View data as" page.

---

### Suggestions

Give users an option to disable these features.[^1]

You can save the user preferences in the browser storage or cache.

[^1]: [An good example is Rust std docs.](https://doc.rust-lang.org/std/index.html)

**Comment by Keith-CY** [comment]
> ### Description
> I want to copy the lock script args and go to another page to search this args, to make sure they are the same args.
> 
> But, after the upgrade in last week (maybe two weeks ago, I guess).
> 
> When I select the args, I could NOT copy it, unless I enable web developer tools and copy it from the source of the page.
> 
> It's really a terrible user experience.
> 
> Maybe you could tell me that, I could copy it from the "View data as" page, but it only can copy the reverse format of the transaction page displayed.
> 
> I have tried all formats in "View data as" page.
> 
> ### Suggestions
> Give users an option to disable these features.[1](#user-content-fn-1-f61c54c709e00f41a345fd316b83f4e6)
> 
> You can save the user preferences in the browser storage or cache.
> 
> ## Footnotes
> 1. [An good example is Rust std docs.](https://doc.rust-lang.org/std/index.html) [↩](#user-content-fnref-1-f61c54c709e00f41a345fd316b83f4e6)

Hi @yangby-cryptape 
Could you show me where you were trying to copy the `lock_script.args`, because I can copy the `args` in `script dialog` by <kbd>cmd + k</kbd> and `copy` in right-click menu

<img width="1108" alt="image" src="https://github.com/nervosnetwork/ckb-explorer/assets/7271329/e63c8346-32d6-4723-acbf-2819e49b3c88">

It's probably a compatibility issue so it would be great if you could share the platform info.

BTW, a dashboard with `settings`(https://github.com/Magickbase/ckb-explorer-public-issues/issues/582) will be enabled later, I will add `disable decoder` in it.

**Comment by Keith-CY** [comment]
> > ### Description
> > I want to copy the lock script args and go to another page to search this args, to make sure they are the same args.
> > But, after the upgrade in last week (maybe two weeks ago, I guess).
> > When I select the args, I could NOT copy it, unless I enable web developer tools and copy it from the source of the page.
> > It's really a terrible user experience.
> > Maybe you could tell me that, I could copy it from the "View data as" page, but it only can copy the reverse format of the transaction page displayed.
> > I have tried all formats in "View data as" page.
> > ### Suggestions
> > Give users an option to disable these features.[1](#user-content-fn-1-f61c54c709e00f41a345fd316b83f4e6)
> > You can save the user preferences in the browser storage or cache.
> > ## Footnotes
> > 
> > 1. [An good example is Rust std docs.](https://doc.rust-lang.org/std/index.html) [↩](#user-content-fnref-1-f61c54c709e00f41a345fd316b83f4e6)
> 
> Hi @yangby-cryptape Could you show me where you were trying to copy the `lock_script.args`, because I can copy the `args` in `script dialog` by cmd + k and `copy` in right-click menu
> 
> <img alt="image" width="1108" src="https://private-user-images.githubusercontent.com/7271329/322251322-e63c8346-32d6-4723-acbf-2819e49b3c88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzU4NDksIm5iZiI6MTcxMzA3NTU0OSwicGF0aCI6Ii83MjcxMzI5LzMyMjI1MTMyMi1lNjNjODM0Ni0zMmQ2LTQ3MjMtYWNiZi0yODE5ZTQ5YjNjODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMDYxOTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmM1NjUxNzliNzI5NGJiMWNkMjFlYmU0OTFmZGJhNThmMmNhZjdhMWRjZDczYjkzOTdmZmNiNzUyYTNmNDgyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kONXPM36H3hlNKrRnuPUKYGE11UizHarVKzRFtKz0NE">
> It's probably a compatibility issue so it would be great if you could share the platform info.
> 
> BTW, a dashboard with `settings`([Magickbase/ckb-explorer-public-issues#582](https://github.com/Magickbase/ckb-explorer-public-issues/issues/582)) will be enabled later, I will add `disable decoder` in it.

I got it in Firefox, it's a compatibility issue

**Comment by Keith-CY** [comment]
> Another terrible user experience: When I search an args in the explorer (I tried with Firefox, I guess Chrome is the same), a window always pops up automatically, and hide the content I searched behind the window.

Can you share a screenshot of how the result is overlapped by the new window

**Comment by Keith-CY** [comment]
> > Can you share a screenshot of how the result is overlapped by the new window
> 
> * After I input `Ctrl+F` (search) in Firefox or Chromium, a search bar (belongs to the browser) will pop up.
> * Then I `Ctrl+V` (paste) the `args` input the search bar, then the "View data as" page will pop up.
> * > I got. Now you can double-click the args to select the string.
>   
>   
>   
>   * Before you fixed this, the "View data as" page will just overlap the `args`.
>   * Now, after you fixed this, the "View data as" page is far away from the `args`.
> * So, I think this bug is fixed too.
> 
> For my personal use case, I think you can close this issue as completed.

Glad to know that the decoder dialog doesn't obstruct interaction on the text in some cases. I just pushed another update to keep the dialog next to the selected text, you may have a try.

I will close this issue if the new position of the dialog works for you.
