### ISSUE TITLE
Discussion about the `hash_type` of xUDT script on testnet

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/ckb-explorer#2072]
### The current xUDT on pudge.explorer.nervos.org
![image](https://github.com/user-attachments/assets/4dc636ff-3f7c-4be6-bc71-d14ea16a0749)
https://pudge.explorer.nervos.org/scripts#xUDT

### The latest xUDT deployment in RFC-0052 is
<img width="758" alt="image" src="https://github.com/user-attachments/assets/a3319187-0d0f-47af-9b57-2c99179de811">

See https://github.com/nervosnetwork/rfcs/blob/abeb01be8c0b1491ac8a1ab3908416e9ab3cc432/rfcs/0052-extensible-udt/0052-extensible-udt.md#deployment

- ref: https://github.com/nervosnetwork/rfcs/pull/428

## **Describe the solution you'd like**
Maybe both the above scripts could be interpreted as xUDT on ckb-testnet-explorer.

## **Describe alternatives you've considered**
Revert the `hash_type` of xUDT back to `type` in the latest RFC docs.
cc @XuJiandong

## References
- https://github.com/Magickbase/ckb-explorer-public-issues/issues/508

**Comment by XuJiandong** [comment]
The current xUDT description on pudge.explorer.nervos.org should use 'data1` instead of `type`. It's not upgradeable.

**Comment by Keith-CY** [comment]
I noticed that only `code hash` and `hash type` were updated in the RFC while the `tx hash` is not(https://github.com/nervosnetwork/rfcs/commit/4c6c76284ca7c94faae23f75be4d1d81ce53e20e)

So the script is still deployed at https://pudge.explorer.nervos.org/transaction/0xbf6fb538763efec2a70a6a3dcb7242787087e1030c4e7d86585bc63a9d337f5f outputs[0]

Its `data hash` matches `0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95`, but its type script is of `type id` and the owner lock is of `secp256_k1`.

How is the upgrade disabled?

**Comment by XuJiandong** [comment]
It's for historical reasons. When it was first deployed on the testnet, we wanted it to be upgradable to fix potential bugs. However, once this final version is deployed, it will not be upgraded.

**Comment by Keith-CY** [comment]
> It's for historical reasons. When it was first deployed on the testnet, we wanted it to be upgradable to fix potential bugs. However, once this final version is deployed, it will not be upgraded.

Got it, the script is upgradable but won't be updated anymore.

The script can be referenced by `type hash` or `data hash`, and only `data hash` is suggested and mentioned in the RFC. Am I right?

**Comment by Keith-CY** [comment]
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/21cebe02-5b89-4362-98ba-504cf8573648">

The reference info of `type hash` and `data hash` will be listed simultaneously
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/c2752cfa-df6d-43fe-8dce-e9546815598a">

Because most on-chain use cases are based on `type hash`

**Comment by Keith-CY** [comment]
Updated
xUDT(final_rls): https://pudge.explorer.nervos.org/script/0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb/type
xUDT: https://pudge.explorer.nervos.org/script/0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95/data1
