### ISSUE TITLE
unexpected BTC tx link

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/ckb-explorer#2093]
### **Describe the bug**
![image](https://github.com/user-attachments/assets/ef4550ca-440c-47d8-a713-37374cfd4b0b)
https://pudge.explorer.nervos.org/transaction/0x83333ed03a9a950b303481978527ca69d3443635fed6c1d89819faf10fecf1cd#0

#### The btc_tx link: https://mempool.space/testnet/tx/f6bd6ca03cc1e847516270a6596b8314e67e4bfce4bf55f43b575fa872b771b3/f6bd6ca03cc1e847516270a6596b8314e67e4bfce4bf55f43b575fa872b771b3

**To Reproduce**
1. Go to 'https://pudge.explorer.nervos.org/transaction/0x83333ed03a9a950b303481978527ca69d3443635fed6c1d89819faf10fecf1cd#0'
2. check output#0 's cell info
3. click the BTC tx link

**Comment by Keith-CY** [comment]
Fixed by https://github.com/nervosnetwork/ckb-explorer-frontend/commit/887aa65d73ec5160abb4fb71f64edbe8462be6c9


https://github.com/user-attachments/assets/116598bb-7a0b-46c1-8523-a514f09357ee

**Comment by Flouse** [comment]
https://explorer.nervos.org/transaction/0x0f3a36905dba1f088ec968ae707699a2b3da07bd4c9cbf241a666a1d840abcaf

When will the mainnet version be updated? Thanks.

**Comment by Flouse** [comment]
![image](https://github.com/user-attachments/assets/e59349de-bcb9-44da-87ae-91e2011e5c9a)


1. The link : https://mempool.space/tx/d7d5e43c288ecba925d2353f669377b39d6af7844faffe2f02d869d1215e66d1/d7d5e43c288ecba925d2353f669377b39d6af7844faffe2f02d869d1215e66d1
2. -> https://mempool.space/

**Comment by Keith-CY** [comment]
> ![image](https://private-user-images.githubusercontent.com/1297478/351668391-e59349de-bcb9-44da-87ae-91e2011e5c9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTYwMDQsIm5iZiI6MTcyMTgxNTcwNCwicGF0aCI6Ii8xMjk3NDc4LzM1MTY2ODM5MS1lNTkzNDlkZS1iY2I5LTQ0ZGEtODdhZS05MWUyMDExZTVjOWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMTAwODI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQyYzA3ZmVjY2M1OGY2MzU3YzdlOTJlYzEwZDI3YjEwMTNkNWUyMDEzNmY1MDZiYWRhMzE5ZjcxMjY2NGVkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y_gKd6oBg02j_qKTCjVzCgD53Cfwq8idcapxC37T_es)
> 
> 1. The link : [mempool.space/tx/d7d5e43c288ecba925d2353f669377b39d6af7844faffe2f02d869d1215e66d1/d7d5e43c288ecba925d2353f669377b39d6af7844faffe2f02d869d1215e66d1](https://mempool.space/tx/d7d5e43c288ecba925d2353f669377b39d6af7844faffe2f02d869d1215e66d1/d7d5e43c288ecba925d2353f669377b39d6af7844faffe2f02d869d1215e66d1)
> 2. -> jumped to [mempool.space](https://mempool.space/)

Just updated, the deployment hung in the queue for an unknown reason.
