### ISSUE TITLE
Is there a plan to add  get_cells_by_lock_hash interface?

### ISSUE THREAD

**Issue by wangke0809** [nervosnetwork/ckb-explorer#330]
When transfer CKB we need to get unspent cells, [get_cells_by_lock_hash](https://github.com/nervosnetwork/ckb/blob/59e7b47f5a1ff50b5a97a9d3aebe27d6681c58ab/rpc/src/module/chain.rs#L177) in full node isn't a good way to do this. Can we add  get_cells_by_lock_hash interface in this project?

**Comment by shaojunda** [comment]
Thank you for your report, we will consider whether to add the interface.

**Comment by ashchan** [comment]
Currently cab-explorer doesn't expose any cache server layer. We hope in the near future the community will build and release such services to support all kinds of apps/businesses.

**Comment by ashchan** [comment]
Please note to get utxo from a remote server/service you'll expose your public keys/lock hashes, which is usually a big privacy concern. Unless running a node locally is out of the question I'd suggest you always have a private node to query.

**Comment by wangke0809** [comment]
> Please note to get utxo from a remote server/service you'll expose your public keys/lock hashes, which is usually a big privacy concern. Unless running a node locally is out of the question I'd suggest you always have a private node to query.

Yes, thank you for your suggestions.
