### ISSUE TITLE
why I can't find sUDT cell on the explorer

### ISSUE THREAD

**Issue by Rbchi** [nervosnetwork/ckb-explorer#605]
https://github.com/nervosnetwork/ckb-explorer/blob/d3375eeaca266b006d480b6f55f0ee38b184f113/.env#L33
Like the topic, I have found you devs update the data and put the type hash on the explorer.
however,why I can't find the type hash on explorer?both Arrogon and Lina,I can't find this sUDT type hash
0x48dbf59b4c7ee1547238021b4869bceedf4eea6b43772e5d66ef8865b6ae7212

**Comment by duanyytop** [comment]
Now we just only support sUDT on Aggron Testnet and if you create a new sUDT by yourself on AggronTestnet, you can find sUDT related transaction data structure on Aggron Explorer.

If you want to see more information about your sUDT on Aggron Explorer , please click Aggron Explorer footer menu “Submit sUDT” and send email with sUDT information to us.

Thanks.

**Comment by Rbchi** [comment]
@duanyytop thanks
This is what I want to ask, I want to check the sUDT cell on Aggron explorer.
However, when I key in the type hash 0x48dbf59b4c7ee1547238021b4869bceedf4eea6b43772e5d66ef8865b6ae7212 on the explorer,I can't find this type hash.What should I do if I want to take a look at the sUDT cell?

**Comment by duanyytop** [comment]
OK. I see.  
Now we just support searching type hash which is in our sUDT whitelist . If your sUDT isn't in our whitelist, you can't search type hash to visit sUDT cells on Aggron explorer.

But you can also visit your sUDT cell by transaction hash. When you issued or transferred or burned your sUDT , you should get a transaction hash and you can search the transaction hash to visit your sUDT cells.

**Comment by Rbchi** [comment]
haha 
what I want to do is searching the type hash you update on the github. 
https://github.com/nervosnetwork/ckb-explorer/blob/d3375eeaca266b006d480b6f55f0ee38b184f113/.env#L33
But when I enter the type hash you implement on the testnet, the explorer reply me that they can't find this type hash,so that's why I felt confused.
like this 
https://explorer.nervos.org/aggron/search/fail?q=0x48dbf59b4c7ee1547238021b4869bceedf4eea6b43772e5d66ef8865b6ae7212

**Comment by shaojunda** [comment]
> 0x48dbf59b4c7ee1547238021b4869bceedf4eea6b43772e5d66ef8865b6ae7212

You two are not talking about a `type hash`, in the `.env` actually is sudt script code hash.

**Comment by shaojunda** [comment]
> haha
> what I want to do is searching the type hash you update on the github.
> https://github.com/nervosnetwork/ckb-explorer/blob/d3375eeaca266b006d480b6f55f0ee38b184f113/.env#L33
> 
> 
> But when I enter the type hash you implement on the testnet, the explorer reply me that they can't find this type hash,so that's why I felt confused.
> like this
> [explorer.nervos.org/aggron/search/fail?q=0x48dbf59b4c7ee1547238021b4869bceedf4eea6b43772e5d66ef8865b6ae7212](https://explorer.nervos.org/aggron/search/fail?q=0x48dbf59b4c7ee1547238021b4869bceedf4eea6b43772e5d66ef8865b6ae7212)

this is a `sUDT` example https://explorer.nervos.org/aggron/sudt/0xbbb3d5666deb0b79db4e4bc3a5c5512d5cd366a7e2f922722286257dcb20dc42

**Comment by Rbchi** [comment]
Thanks junda for help
I just find that is a code hash. Sorry I am a CKB enthusiast but also a ckb Programming noob.
Could I confirm one more time: the `SUDT_CELL_TYPE_HASH` field is a **code hash**,instead of type hash,that's why I search nothing on the testnet when I key this field and search?

**Comment by shaojunda** [comment]
> Thanks junda for help
> I just find that is a code hash. Sorry I am a CKB enthusiast but also a ckb Programming noob.
> Could I confirm one more time: the `SUDT_CELL_TYPE_HASH` field is a **code hash**,instead of type hash,that's why I search nothing on the testnet when I key this field and search?

Yes, I named it `XXX_TYPE_HASH` because the `sUDT` Script's `hash_type` is `type`, but actually it's a `code_hash`

**Comment by shaojunda** [comment]
> Thanks junda for help
> I just find that is a code hash. Sorry I am a CKB enthusiast but also a ckb Programming noob.
> Could I confirm one more time: the `SUDT_CELL_TYPE_HASH` field is a **code hash**,instead of type hash,that's why I search nothing on the testnet when I key this field and search?

Maybe `SUDT_CELL_CODE_HASH` will be clearer.

**Comment by Rbchi** [comment]
So very thankful for two CKB devs replying my question patiently!
