### ISSUE TITLE
Have you considered supporting utxo queries?

### ISSUE THREAD

**Issue by wo4zhuzi** [nervosnetwork/ckb-explorer#707]

**Comment by shaojunda** [comment]
Can you describe your needs in detail? Does `utxo query` mean `cell query`?

**Comment by wo4zhuzi** [comment]
> Can you describe your needs in detail? Does `utxo query` mean `cell query`? Why do you think Explorer needs to provide `cell` query?

Offline signature will use relevant parameters

**Comment by shaojunda** [comment]
Explorer‘s API is only provided for the front end of the Explore, so it is recommended that you use other methods to collect cells, such as SDK or https://github.com/nervosnetwork/lumos

**Comment by shaojunda** [comment]
Or you can use https://github.com/quake/ckb-indexer to collect cells

**Comment by shaojunda** [comment]
This issue will be closed if no further activity occurs. Thank you for your contributions.

**Comment by wo4zhuzi** [comment]
> This issue will be closed if no further activity occurs. Thank you for your contributions.
OK. thanks
