### ISSUE TITLE
Question: where could I see the each epoch time cost?

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb-explorer#787]
I saw a real-time "Estimated Epoch Time".
I saw the chart of "Epoch Time Distribution".

But I didn't find any values or charts to display the time cost for each epoch.

Just like the chart of "Average Block Time", could explorer add a chart for "Epoch Time"?
A chart for "Epoch Time & Difficulty" is better.

**Comment by shaojunda** [comment]
Similar functions will be launched soon. https://github.com/nervosnetwork/ckb-explorer-internal/issues/870

**Comment by shaojunda** [comment]
Similar functions will be launched soon.

**Comment by shaojunda** [comment]
please see: https://explorer.nervos.org/charts/difficulty-uncle-rate

**Comment by yangby-cryptape** [comment]
Cool!
