### ISSUE TITLE
Transaction history (ERC20 Transfers) bug

### ISSUE THREAD

**Issue by shilohusa** [nervosnetwork/ckb-explorer#879]
I am able to see the harvested  transaction in YOK value under ERC20 Transfers. This is good news however some of the transactions are showing in very big number ( For Example. I highlighted in yellow color). I think that is bug. Can you ask your IT team to check this.  I never did that kind of big transactions.
![image](https://user-images.githubusercontent.com/100814467/156476691-d1fe5dbc-ee58-4022-a1c4-b91bc73f10d5.png)

I already contacted the Discord Nervos support. They asked me to create an issues here.

**Comment by shilohusa** [comment]
I am just giving another example...I harvested  752428.64 KOI coin from the FARM but it's showing this 752,428,644,318,517,289,424,985 number in ERC20 Transfers transactions.

**Comment by Keith-CY** [comment]
Hi @shilohusa , I've reposted this issue in https://github.com/nervina-labs/godwoken_explorer/issues/245 since the screenshot indicates that it's a godwoken explorer, not a ckb explorer.
