### ISSUE TITLE
Negative DAO deposit value

### ISSUE THREAD

**Issue by ShiningRay** [nervosnetwork/ckb-explorer#936]
The address [ckt1q3vvtay34wndv9nckl8hah6fzzcltcqwcrx79apwp2a5lkd07fdxxsm6mz3zemkn8j7yuesl3men64arjrfgwfr89d8](
https://pudge.explorer.nervos.org/address/ckt1q3vvtay34wndv9nckl8hah6fzzcltcqwcrx79apwp2a5lkd07fdxxsm6mz3zemkn8j7yuesl3men64arjrfgwfr89d8) has negative DAO balance value

**Comment by ShiningRay** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/937

**Comment by Keith-CY** [comment]
Still negative
![image](https://user-images.githubusercontent.com/7271329/181081191-2c1a1a11-e024-4faa-bf69-759f9008e126.png)

**Comment by Keith-CY** [comment]
Now this address has no deposit but earns compensation
![image](https://user-images.githubusercontent.com/7271329/194691642-d51c6924-dfc5-4b07-828d-c0815171b796.png)

Maybe we should fetch its live cells and check if there's a cell in the dao.

**Comment by ShiningRay** [comment]
Has been fixed in https://github.com/nervosnetwork/ckb-explorer/pull/937
